### ISSUE TITLE
What is "error" in the grammar?

### ISSUE THREAD

**Issue by CapacitorSet** [Northern-Lights/yara-parser#12]
I'm almost done with the expression parsing, but I can't figure out what this rule does ([`grammar.y:444`](https://github.com/Northern-Lights/yara-parser/blob/master/grammar/grammar.y#L444)):

    _FOR_ for_expression error

There seems to be no "error", neither in the yacc file nor in the flex one.

**Comment by CapacitorSet** [comment]
And while you're at it, what's this?

    '-' primary_expression %prec UNARY_MINUS

**Comment by Northern-Lights** [comment]
These are both bison/yacc things.  They're part of the original YARA grammar files.  I am not sure why an error is allowed, but it came from here: https://github.com/VirusTotal/yara/blob/master/libyara/grammar.y#L1031  @plusvic would have a better idea of why it's there.  I see that a YYERROR is thrown in the original libyara, so maybe it's handled elsewhere in libyara and should not be a valid production in yara-parser.

Here is more info on error: https://www.gnu.org/software/bison/manual/bison.html#Simple-Error-Recovery

Here is more info on %prec, which stands for "precedence:" https://www.gnu.org/software/bison/manual/bison.html#Using-Precedence

**Comment by Northern-Lights** [comment]
As for the _UNARY_MINUS_, you're right.  It doesn't look like the lexer emits it at all.

**Comment by plusvic** [comment]
In bison grammars `error` is an special token that bison puts in the token stream for indicating that an error occurred during parsing. By accepting the `error` token in your grammar you have the opportunity to recover from errors at certain points. For example, in the following snippet the `error` token is used for recovering from errors occurred while parsing a rule and keep parsing at the next rule, import statement or include statement.
```
rules
    : /* empty */
    | rules rule
    | rules import
    | rules error rule      /* on error skip until next rule..*/
    | rules error import    /* .. or import statement */
    | rules error "include" /* .. or include statement */
    ;
```

Without this the parser would abort as soon as it encounters an error and wouldn't continue with the next rule. In the case of `_FOR_ for_expression error` the objective is not recovering from the error, as the error is re-issued with `YYERROR`, it's just decrementing the `compiler->loop_depth` variable even in the case of an error. So this is not necessary in your case if you don't have any data structure that need to recover its previous state after a parsing error occurs inside a `for` statement.

`UNARY_MINUS` is not emitted by the lexer, it is an artificial terminal symbol used for establishing the precedence of the unary minus. Check this: https://www.gnu.org/software/bison/manual/html_node/Contextual-Precedence.html

**Comment by CapacitorSet** [comment]
Nice to have @plusvic himself chime in. Thank you!

@Northern-Lights, with this I finished implementing the actions. Can you give feedback on the PR and the post-processing thing when you have time?
