### ISSUE TITLE
XOR modifier doesn't work when bytes range is provided

### ISSUE THREAD

**Issue by SaretX** [Northern-Lights/yara-parser#18]
When one specifies bytes range for xor modifier, e.g.: `$xor_string = "This program cannot" xor(0x01-0xff)`, parser throws an error: 

> Parser result: "1" grammar: lexical error @4: "syntax error: unexpected '(', expecting _CONDITION_"

**Comment by Northern-Lights** [comment]
Thanks for reporting. The parser needs to be updated to line up with the latest yara. I hope to get to it soon but will of course accept PRs if members of the community can get to it more quickly

**Comment by SaretX** [comment]
Will try to figure out how all this works and make up a PR, don't have a previous experience with lexers/parsers though, so I'm not sure that I can handle it..

**Comment by Northern-Lights** [comment]
The basic process is to gut the actions in the parser and add our Go-specific code in there. A diff tool might help, but there will be manual work involved.

You'll probably have to add "xor" as a new token. It will be in the same situation as "nocase" and "full word" and others, so looking at the code there may help as a guide.

Lastly, you will have to add a new field to the string modifiers type. Again, nocase and fullword should provide decent guidance as to what needs to be done
